### ISSUE TITLE
Tighten license - move to Affero 3

### ISSUE THREAD

**Issue by jamescooke** [prlint/prlintapi#55]
Last tag under MIT is https://github.com/prlint/prlintapi/releases/tag/v0.1-mit - will move forward under [GNU Affero 3](https://opensource.org/licenses/AGPL-3.0)

I'm doing this so that this project can have a possible (as I see it) protected route to being able to support itself - that means limiting what others can do with the software commercially.

## Project goals

* Support open source projects that need to ensure pull request quality by providing this PRLint API hosted on prlint.com free for open / public repositories.
* Support businesses that care about the quality of their git repositories:
  - Near term, (installed route) they can install a copy of the software on their servers and configure it to run on their closed / private repositories.
  - Long term, (paid route) prlint.com offers private repositories access for a fee that is used to support this project by paying for development time and hosting costs.

## Reasoning

IMO Affero 3 protects the project from businesses that PRLint intends to support from cannibalising the paid route of support. That scenario would be possible if business B took a copy of PRLint, made improvements and hosted it on their own service to compete with prlint.com's offering to businesses with private repositories. Affero 3 would assert that business B would be obliged to publish their changes to the software - although of course, they might have created other unique work such as better customer support / integration / services on top what is provided in the project, which would not be covered.

## Community

I would love this to grow into a community project (note to self to add more community / contribution docs). If you're reading this and have feedback, please comment, even if this is closed.

**Comment by andrew** [comment]
👏
